### ISSUE TITLE
OpenStruct breaks some hash functionalities on JRuby

### ISSUE THREAD

**Issue by thomas07vt** [linhchauatl/config_service#1]
```
NoMethodError: undefined method `[]' for #<OpenStruct en="ENU", cs="CZS", da="DAN", de="DEU", es="ESN", fi="FIN", fr="FRA", hu="HUN", it="ITA", ja="JPN", jp="JPN", ko="KOR", nl="DUT", no="NOR", pl="POL", pt_BR="PTB", ru="RUS", sv="SWE", zh_CN="CHS", zh_TW="CHT">
```

**Comment by thomas07vt** [comment]
So this is just an issue with JRuby OpenStruct's (tested with jruby-1.7.19)

**Comment by thomas07vt** [comment]
So I am thinking this might be better than opening up OpenStruct entirely. Just adding a module that does the delegation:
--------------------------------

class HashUtils
  class << self
    def hash_to_open_struct(data_hash)
      elements_with_hash_values = data_hash.select { |key, value|  value.is_a? Hash }
      return OpenStruct.new(data_hash) if elements_with_hash_values.empty?

      result = OpenStruct.new(data_hash.select { |key, value|  !value.is_a?(Hash) })
      elements_with_hash_values.each do |key, value|
        result.send("#{key}=", hash_to_open_struct(value))
      end
      
      result.extend(OpenStructHashable) if RUBY_PLATFORM == "java"

      result
    end
  end
end

module OpenStructHashable
  delegate :[], to: :@table
end

**Comment by linhchauatl** [comment]
I agree.
